In [1]:
import numpy as np




a = np.array([[1,0,0],[0,1,0],[0,0,0]])
a_adj = cal_adj(a)
print(a_adj)

[1, 2]


LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [2]:
a[(1,2),(0,1)]

array([0, 0])

In [3]:
a[[1,2,3,4]]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [4]:
a[1,2,3,4]

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

In [5]:
a[2]

array([0, 0, 0])

In [6]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [7]:
a[1,2]

0

In [8]:
b = np.random.rand(10,10)


In [9]:
b[1:2,2:3]

array([[0.46616211]])

In [10]:
b[1:5,2:5]

array([[0.46616211, 0.71459691, 0.52827888],
       [0.55073691, 0.08908274, 0.75654115],
       [0.64070356, 0.73392578, 0.06475347],
       [0.60743995, 0.62208062, 0.82420147]])

In [11]:
b[[1,2,3],[1,2,3]]

array([0.76120921, 0.55073691, 0.73392578])

In [12]:
b[[1,2,3],[3]]

array([0.71459691, 0.08908274, 0.73392578])

In [13]:
b[[1,2,3,4,5,6],1:3]

array([[0.76120921, 0.46616211],
       [0.08746998, 0.55073691],
       [0.10122434, 0.64070356],
       [0.76030654, 0.60743995],
       [0.49745982, 0.99904429],
       [0.00525391, 0.13144033]])

In [14]:
b[[1,2,3,4,5,6],1:4]

array([[0.76120921, 0.46616211, 0.71459691],
       [0.08746998, 0.55073691, 0.08908274],
       [0.10122434, 0.64070356, 0.73392578],
       [0.76030654, 0.60743995, 0.62208062],
       [0.49745982, 0.99904429, 0.76549901],
       [0.00525391, 0.13144033, 0.64612807]])

In [15]:
b[1:10]

array([[6.54674280e-01, 7.61209206e-01, 4.66162114e-01, 7.14596910e-01,
        5.28278884e-01, 4.80604306e-01, 3.82918993e-01, 6.06584320e-01,
        5.56953232e-01, 5.99374523e-01],
       [5.05898065e-01, 8.74699822e-02, 5.50736913e-01, 8.90827423e-02,
        7.56541146e-01, 9.05104504e-01, 5.09682686e-02, 7.52212030e-04,
        8.22166370e-01, 7.96395550e-01],
       [8.56144423e-01, 1.01224338e-01, 6.40703556e-01, 7.33925775e-01,
        6.47534706e-02, 6.21268561e-01, 3.49835449e-01, 1.36067536e-01,
        2.73166798e-01, 1.17691046e-01],
       [4.97332437e-01, 7.60306536e-01, 6.07439948e-01, 6.22080619e-01,
        8.24201468e-01, 3.16968121e-01, 8.69708206e-01, 9.19797855e-01,
        2.07514480e-01, 8.13750540e-01],
       [5.28453961e-01, 4.97459824e-01, 9.99044293e-01, 7.65499007e-01,
        3.01315805e-01, 5.96293680e-01, 2.44445401e-01, 1.12920994e-01,
        7.60072410e-01, 4.48825272e-01],
       [5.51534282e-02, 5.25390601e-03, 1.31440328e-01, 6.46128066e-01,
   

In [16]:
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [17]:
a[0,2]

0

In [18]:
a[[0,2]]

array([[1, 0, 0],
       [0, 0, 0]])

In [19]:
a[[0,2]][[0,2]]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [20]:
a[[0,2]][0,2]

0

In [21]:
a[[0,2]].shape

(2, 3)

In [22]:
a[[0,2]][:,[0,2]]

array([[1, 0],
       [0, 0]])

In [23]:
import numpy as np

def cal_adj(a:np.array):
    assert a.shape[0] == a.shape[1]
    n = a.shape[0]
    b = np.zeros((n,n))
    for i in range(n):
        x_index = list(range(n))
        x_index.remove(i)
        for j in range(n):
            y_index = list(range(n))
            y_index.remove(j)
            b[i,j] = np.linalg.det(a[x_index][:,y_index])
    return(b.T)


a = np.array([[1,0,0],[0,1,0],[0,0,0]])
a_adj = cal_adj(a)
print("矩阵伴随为:")
print(a_adj)
print("-"*40)

矩阵伴随为:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
----------------------------------------


In [24]:
vals1,vecs1= np.linalg.eig(a)

In [25]:
vals1,vecs1= np.linalg.eig(a_adj)

In [26]:
vals2,vecs2= np.linalg.eig(a_adj)

In [27]:
vals1,vecs1= np.linalg.eig(a)

In [28]:
vecs1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
vecs2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])